#!/usr/bin/env node
'use strict';

/**
 * Call any documented ScraperSocial endpoint by path. Only paths present in
 * the bundled endpoints.json catalogue are accepted; anything else is refused
 * before a request is made. Flags become query parameters.
 *
 *   node call_endpoint.js /v1/reddit/subreddit --handle programming --limit 10
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { readFileSync } = require('node:fs');
const { join } = require('node:path');
const { callEndpoint, main, parseFlags, usage } = require('./_client.js');

const catalog = JSON.parse(readFileSync(join(__dirname, 'endpoints.json'), 'utf8'));
// Endpoints that return a person's contact details are never callable from
// this generic script. They stay in the catalogue, flagged personalData: true,
// so list_endpoints.js can say they exist and point at the platform skill.
const ALLOWED = new Set(catalog.endpoints.filter((e) => !e.personalData).map((e) => e.path));
const EXCLUDED = new Set(catalog.endpoints.filter((e) => e.personalData).map((e) => e.path));
const { _, flags } = parseFlags(process.argv.slice(2));
const path = _[0];

if (path && EXCLUDED.has(path)) {
  usage(
    path + ' returns personal contact details and is not callable from this skill. ' +
      'Use the platform skill, which documents when that is appropriate.'
  );
}
if (!path || !ALLOWED.has(path)) {
  usage(
    'Usage: node call_endpoint.js /v1/<platform>/<capability> [--param value ...]\n' +
      'Only documented endpoints are accepted; run list_endpoints.js to see them.' +
      (path ? ' Got: ' + path : '')
  );
}

const params = {};
for (const [name, value] of Object.entries(flags)) {
  if (name === 'include_email') {
    process.stderr.write('note: include_email is not supported by this skill and was dropped.\n');
    continue;
  }
  params[name] = value === true ? 'true' : value;
}

main(() => callEndpoint(path, params));
