#!/usr/bin/env node
'use strict';

/**
 * Call any ScraperSocial endpoint by path. Flags become query parameters.
 *
 *   node call_endpoint.js /v1/reddit/subreddit --handle programming --limit 10
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, main, parseFlags, usage } = require('./_client.js');

const { _, flags } = parseFlags(process.argv.slice(2));
const path = _[0];

if (!path || !path.startsWith('/v1/')) {
  usage('Usage: node call_endpoint.js /v1/<platform>/<capability> [--param value ...]');
}

const params = {};
for (const [name, value] of Object.entries(flags)) {
  params[name] = value === true ? 'true' : value;
}

main(() => callEndpoint(path, params));
