#!/usr/bin/env node
'use strict';

/**
 * Call any documented ScraperSocial endpoint by path. Only paths present in
 * the bundled endpoints.json catalogue are accepted; anything else is refused
 * before a request is made. Flags become query parameters.
 *
 *   node call_endpoint.js /v1/reddit/subreddit --handle programming --limit 10
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { readFileSync } = require('node:fs');
const { join } = require('node:path');
const { callEndpoint, main, parseFlags, usage } = require('./_client.js');

const catalog = JSON.parse(readFileSync(join(__dirname, 'endpoints.json'), 'utf8'));
const ALLOWED = new Set(catalog.endpoints.map((e) => e.path));
const { _, flags } = parseFlags(process.argv.slice(2));
const path = _[0];

if (!path || !ALLOWED.has(path)) {
  usage(
    'Usage: node call_endpoint.js /v1/<platform>/<capability> [--param value ...]\n' +
      'Only documented endpoints are accepted; run list_endpoints.js to see them.' +
      (path ? ' Got: ' + path : '')
  );
}

const params = {};
for (const [name, value] of Object.entries(flags)) {
  params[name] = value === true ? 'true' : value;
}

main(() => callEndpoint(path, params));
