#!/usr/bin/env node
'use strict';

/**
 * List every endpoint this repo knows about. Reads a bundled snapshot, so it
 * costs nothing and needs no API key.
 *
 *   node list_endpoints.js                 # all platforms
 *   node list_endpoints.js --platform tiktok
 *   node list_endpoints.js --search transcript
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { readFileSync } = require('node:fs');
const { join } = require('node:path');
const { parseFlags } = require('./_client.js');

const catalog = JSON.parse(readFileSync(join(__dirname, 'endpoints.json'), 'utf8'));
const { flags } = parseFlags(process.argv.slice(2));

let rows = catalog.endpoints;
if (flags.platform) rows = rows.filter((e) => e.platform === flags.platform);
if (flags.search) {
  const needle = String(flags.search).toLowerCase();
  rows = rows.filter((e) => (e.path + ' ' + e.summary).toLowerCase().includes(needle));
}

process.stdout.write(JSON.stringify({ count: rows.length, endpoints: rows }, null, 2) + '\n');
