#!/usr/bin/env node
'use strict';

/**
 * Call any documented TikTok endpoint by path, including ones that
 * have no dedicated script. Only the paths listed in ALLOWED (the same set
 * documented in SKILL.md) are accepted; anything else is refused before a
 * request is made. Every flag after the path is passed through as a query
 * parameter.
 *
 *   node call_endpoint.js /v1/tiktok/<capability> --handle nasa --limit 20
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, main, parseFlags, usage } = require('./_client.js');

const PREFIX = '/v1/tiktok/';
const ALLOWED = new Set(["/v1/tiktok/channel-reposts","/v1/tiktok/channel-stats","/v1/tiktok/channel-top-videos","/v1/tiktok/channel-videos","/v1/tiktok/comments","/v1/tiktok/followers","/v1/tiktok/following","/v1/tiktok/hashtag-search","/v1/tiktok/search","/v1/tiktok/song","/v1/tiktok/song-videos","/v1/tiktok/stats","/v1/tiktok/summary","/v1/tiktok/top-search","/v1/tiktok/transcript","/v1/tiktok/user-search"]);
const { _, flags } = parseFlags(process.argv.slice(2));
const path = _[0];

if (!path) {
  usage('Usage: node call_endpoint.js ' + PREFIX + '<capability> [--param value ...]');
}
if (!ALLOWED.has(path)) {
  usage(
    'This script only calls the documented ' + PREFIX + '* endpoints. Got: ' + path +
      '\nAllowed:\n  ' + [...ALLOWED].join('\n  ')
  );
}

const params = {};
for (const [name, value] of Object.entries(flags)) {
  params[name] = value === true ? 'true' : value;
}

main(() => callEndpoint(path, params));
