#!/usr/bin/env node
'use strict';

/**
 * TikTok: channel
 *
 *   --section=reposts -> /v1/tiktok/channel-reposts — 3 credits per video
 *   --section=stats -> /v1/tiktok/channel-stats — 3 credits
 *   --section=top-videos -> /v1/tiktok/channel-top-videos — 3 credits per video
 *   --section=videos -> /v1/tiktok/channel-videos — 3 credits per video
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "reposts": { path: "/v1/tiktok/channel-reposts", input: "handle" },
  "stats": { path: "/v1/tiktok/channel-stats", input: "handle" },
  "top-videos": { path: "/v1/tiktok/channel-top-videos", input: "handle" },
  "videos": { path: "/v1/tiktok/channel-videos", input: "handle" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_channel.js <input> --section=<reposts|stats|top-videos|videos>\nSections: reposts, stats, top-videos, videos");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_channel.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
