#!/usr/bin/env node
'use strict';

/**
 * TikTok: audience
 *
 *   --section=followers -> /v1/tiktok/followers — 3 credits per profile
 *   --section=following -> /v1/tiktok/following — 3 credits per profile
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "followers": { path: "/v1/tiktok/followers", input: "handle", list: true },
  "following": { path: "/v1/tiktok/following", input: "handle", list: true },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_audience.js <input> --section=<followers|following>\nSections: followers, following");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_audience.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
