#!/usr/bin/env node
'use strict';

/**
 * TikTok: song
 *
 *   (default) -> /v1/tiktok/song — 3 credits
 *   --section=videos -> /v1/tiktok/song-videos — 3 credits per video
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "default": { path: "/v1/tiktok/song", input: "url" },
  "videos": { path: "/v1/tiktok/song-videos", input: "url" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section || 'default';
if (!SECTIONS[section]) {
  usage("Usage: node get_song.js <input> [--section=<videos>]\nOmit --section for song (/v1/tiktok/song).\nSections: videos");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_song.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
