#!/usr/bin/env node
'use strict';

/**
 * TikTok: search
 *
 *   (default) -> /v1/tiktok/search — 4 credits per result
 *   --section=hashtag-search -> /v1/tiktok/hashtag-search — 3 credits per result
 *   --section=top-search -> /v1/tiktok/top-search — 4 credits per result
 *   --section=user-search -> /v1/tiktok/user-search — 3 credits per profile
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "default": { path: "/v1/tiktok/search", input: "query" },
  "hashtag-search": { path: "/v1/tiktok/hashtag-search", input: "query" },
  "top-search": { path: "/v1/tiktok/top-search", input: "query" },
  "user-search": { path: "/v1/tiktok/user-search", input: "query" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section || 'default';
if (!SECTIONS[section]) {
  usage("Usage: node search.js <input> [--section=<hashtag-search|top-search|user-search>]\nOmit --section for search (/v1/tiktok/search).\nSections: hashtag-search, top-search, user-search");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node search.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
