#!/usr/bin/env node
'use strict';

/**
 * Call any documented X (Twitter) endpoint by path, including ones that
 * have no dedicated script. Only the paths listed in ALLOWED (the same set
 * documented in SKILL.md) are accepted; anything else is refused before a
 * request is made. Every flag after the path is passed through as a query
 * parameter.
 *
 *   node call_endpoint.js /v1/twitter/<capability> --handle nasa --limit 20
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, main, parseFlags, usage } = require('./_client.js');

const PREFIX = '/v1/twitter/';
const ALLOWED = new Set(["/v1/twitter/list-tweets","/v1/twitter/profile","/v1/twitter/search","/v1/twitter/stats","/v1/twitter/summary","/v1/twitter/transcript","/v1/twitter/tweets"]);
const { _, flags } = parseFlags(process.argv.slice(2));
const path = _[0];

if (!path) {
  usage('Usage: node call_endpoint.js ' + PREFIX + '<capability> [--param value ...]');
}
if (!ALLOWED.has(path)) {
  usage(
    'This script only calls the documented ' + PREFIX + '* endpoints. Got: ' + path +
      '\nAllowed:\n  ' + [...ALLOWED].join('\n  ')
  );
}

const params = {};
for (const [name, value] of Object.entries(flags)) {
  params[name] = value === true ? 'true' : value;
}

main(() => callEndpoint(path, params));
