#!/usr/bin/env node
'use strict';

/**
 * Call any documented Facebook endpoint by path, including ones that
 * have no dedicated script. Only the paths listed in ALLOWED (the same set
 * documented in SKILL.md) are accepted; anything else is refused before a
 * request is made. Every flag after the path is passed through as a query
 * parameter.
 *
 *   node call_endpoint.js /v1/facebook/<capability> --handle nasa --limit 20
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, main, parseFlags, usage } = require('./_client.js');

const PREFIX = '/v1/facebook/';
const ALLOWED = new Set(["/v1/facebook/ad","/v1/facebook/ads-search","/v1/facebook/channel-posts","/v1/facebook/comment-replies","/v1/facebook/comments","/v1/facebook/download","/v1/facebook/event","/v1/facebook/events-search","/v1/facebook/followers","/v1/facebook/following","/v1/facebook/group-posts","/v1/facebook/marketplace-item","/v1/facebook/marketplace-search","/v1/facebook/page-ads","/v1/facebook/page-events","/v1/facebook/page-search","/v1/facebook/page-stats","/v1/facebook/photos","/v1/facebook/reels","/v1/facebook/reviews","/v1/facebook/stats","/v1/facebook/summary","/v1/facebook/transcript"]);
const { _, flags } = parseFlags(process.argv.slice(2));
const path = _[0];

if (!path) {
  usage('Usage: node call_endpoint.js ' + PREFIX + '<capability> [--param value ...]');
}
if (!ALLOWED.has(path)) {
  usage(
    'This script only calls the documented ' + PREFIX + '* endpoints. Got: ' + path +
      '\nAllowed:\n  ' + [...ALLOWED].join('\n  ')
  );
}

const params = {};
for (const [name, value] of Object.entries(flags)) {
  params[name] = value === true ? 'true' : value;
}

main(() => callEndpoint(path, params));
