#!/usr/bin/env node
'use strict';

/**
 * Facebook: marketplace
 *
 *   --section=item -> /v1/facebook/marketplace-item — 3 credits
 *   --section=search -> /v1/facebook/marketplace-search — 3 credits per listing
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "item": { path: "/v1/facebook/marketplace-item", input: "url" },
  "search": { path: "/v1/facebook/marketplace-search", input: "query" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_marketplace.js <input> --section=<item|search>\nSections: item, search");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_marketplace.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
