#!/usr/bin/env node
'use strict';

/**
 * Facebook: page
 *
 *   --section=ads -> /v1/facebook/page-ads — 4 credits per ad
 *   --section=events -> /v1/facebook/page-events — 3 credits per event
 *   --section=search -> /v1/facebook/page-search — 4 credits per page
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "ads": { path: "/v1/facebook/page-ads", input: "url|handle" },
  "events": { path: "/v1/facebook/page-events", input: "url|handle" },
  "search": { path: "/v1/facebook/page-search", input: "query" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_page.js <input> --section=<ads|events|search>\nSections: ads, events, search");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_page.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
