#!/usr/bin/env node
'use strict';

/**
 * Facebook: stats
 *
 *   (default) -> /v1/facebook/stats — 5 credits
 *   --section=page-stats -> /v1/facebook/page-stats — 10 credits
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "default": { path: "/v1/facebook/stats", input: "url", list: false },
  "page-stats": { path: "/v1/facebook/page-stats", input: "url|handle", list: false },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section || 'default';
if (!SECTIONS[section]) {
  usage("Usage: node get_stats.js <input> [--section=<page-stats>]\nOmit --section for stats (/v1/facebook/stats).\nSections: page-stats");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_stats.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
