#!/usr/bin/env node
'use strict';

/**
 * Facebook: posts
 *
 *   --section=channel-posts -> /v1/facebook/channel-posts — 3 credits per post
 *   --section=group-posts -> /v1/facebook/group-posts — 3 credits per post
 *   --section=photos -> /v1/facebook/photos — 3 credits per photo
 *   --section=reels -> /v1/facebook/reels — 3 credits per reel
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "channel-posts": { path: "/v1/facebook/channel-posts", input: "url|handle" },
  "group-posts": { path: "/v1/facebook/group-posts", input: "url|handle" },
  "photos": { path: "/v1/facebook/photos", input: "url|handle" },
  "reels": { path: "/v1/facebook/reels", input: "url|handle" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_posts.js <input> --section=<channel-posts|group-posts|photos|reels>\nSections: channel-posts, group-posts, photos, reels");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_posts.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
