#!/usr/bin/env node
'use strict';

/**
 * Facebook: events
 *
 *   --section=event -> /v1/facebook/event — 3 credits
 *   --section=search -> /v1/facebook/events-search — 3 credits per event
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "event": { path: "/v1/facebook/event", input: "url", list: false },
  "search": { path: "/v1/facebook/events-search", input: "query", list: true },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_events.js <input> --section=<event|search>\nSections: event, search");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_events.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
