#!/usr/bin/env node
'use strict';

/**
 * Facebook: comments
 *
 *   (default) -> /v1/facebook/comments — 3 credits per comment
 *   --section=comment-replies -> /v1/facebook/comment-replies — 3 credits per reply
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "default": { path: "/v1/facebook/comments", input: "url" },
  "comment-replies": { path: "/v1/facebook/comment-replies", input: "url" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section || 'default';
if (!SECTIONS[section]) {
  usage("Usage: node get_comments.js <input> [--section=<comment-replies>]\nOmit --section for comments (/v1/facebook/comments).\nSections: comment-replies");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_comments.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
