#!/usr/bin/env node
'use strict';

/**
 * GitHub: repo
 *
 *   (default) -> /v1/github/repo — 1 credit
 *   --section=commits -> /v1/github/repo-commits — 1 credit per commit
 *   --section=contributors -> /v1/github/repo-contributors — 1 credit per contributor
 *   --section=issues -> /v1/github/repo-issues — 1 credit per issue
 *   --section=languages -> /v1/github/repo-languages — 1 credit per language
 *   --section=releases -> /v1/github/repo-releases — 1 credit per release
 *   --section=search -> /v1/github/repo-search — 1 credit per repo
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "default": { path: "/v1/github/repo", input: "handle" },
  "commits": { path: "/v1/github/repo-commits", input: "handle" },
  "contributors": { path: "/v1/github/repo-contributors", input: "handle" },
  "issues": { path: "/v1/github/repo-issues", input: "handle" },
  "languages": { path: "/v1/github/repo-languages", input: "handle" },
  "releases": { path: "/v1/github/repo-releases", input: "handle" },
  "search": { path: "/v1/github/repo-search", input: "query" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section || 'default';
if (!SECTIONS[section]) {
  usage("Usage: node get_repo.js <input> [--section=<commits|contributors|issues|languages|releases|search>]\nOmit --section for repo (/v1/github/repo).\nSections: commits, contributors, issues, languages, releases, search");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_repo.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
