#!/usr/bin/env node
'use strict';

/**
 * GitHub: repos
 *
 *   --section=org-repos -> /v1/github/org-repos — 1 credit per repo
 *   --section=user-repos -> /v1/github/user-repos — 1 credit per repo
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "org-repos": { path: "/v1/github/org-repos", input: "handle" },
  "user-repos": { path: "/v1/github/user-repos", input: "handle" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_repos.js <input> --section=<org-repos|user-repos>\nSections: org-repos, user-repos");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_repos.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
