#!/usr/bin/env node
'use strict';

/**
 * Call any documented Instagram endpoint by path, including ones that
 * have no dedicated script. Only the paths listed in ALLOWED (the same set
 * documented in SKILL.md) are accepted; anything else is refused before a
 * request is made. Every flag after the path is passed through as a query
 * parameter.
 *
 *   node call_endpoint.js /v1/instagram/<capability> --handle nasa --limit 20
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, main, parseFlags, usage } = require('./_client.js');

const PREFIX = '/v1/instagram/';
const ALLOWED = new Set(["/v1/instagram/channel-posts","/v1/instagram/channel-reels","/v1/instagram/channel-stats","/v1/instagram/comments","/v1/instagram/download","/v1/instagram/hashtag-analytics","/v1/instagram/hashtag-posts","/v1/instagram/hashtag-reels","/v1/instagram/hashtag-search","/v1/instagram/hashtag-stats","/v1/instagram/keyword-search","/v1/instagram/location-posts","/v1/instagram/location-search","/v1/instagram/location-stats","/v1/instagram/profile-about","/v1/instagram/profile-full","/v1/instagram/profile-search","/v1/instagram/reels-search","/v1/instagram/similar","/v1/instagram/stats","/v1/instagram/summary","/v1/instagram/tagged","/v1/instagram/transcript"]);
const { _, flags } = parseFlags(process.argv.slice(2));
const path = _[0];

if (!path) {
  usage('Usage: node call_endpoint.js ' + PREFIX + '<capability> [--param value ...]');
}
if (!ALLOWED.has(path)) {
  usage(
    'This script only calls the documented ' + PREFIX + '* endpoints. Got: ' + path +
      '\nAllowed:\n  ' + [...ALLOWED].join('\n  ')
  );
}

const params = {};
for (const [name, value] of Object.entries(flags)) {
  params[name] = value === true ? 'true' : value;
}

main(() => callEndpoint(path, params));
