#!/usr/bin/env node
'use strict';

/**
 * Instagram: hashtag
 *
 *   --section=analytics -> /v1/instagram/hashtag-analytics — 3 credits
 *   --section=posts -> /v1/instagram/hashtag-posts — 2 credits per post
 *   --section=reels -> /v1/instagram/hashtag-reels — 2 credits per reel
 *   --section=search -> /v1/instagram/hashtag-search — 2 credits per hashtag
 *   --section=stats -> /v1/instagram/hashtag-stats — 2 credits
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "analytics": { path: "/v1/instagram/hashtag-analytics", input: "query" },
  "posts": { path: "/v1/instagram/hashtag-posts", input: "query" },
  "reels": { path: "/v1/instagram/hashtag-reels", input: "query" },
  "search": { path: "/v1/instagram/hashtag-search", input: "query" },
  "stats": { path: "/v1/instagram/hashtag-stats", input: "query" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_hashtag.js <input> --section=<analytics|posts|reels|search|stats>\nSections: analytics, posts, reels, search, stats");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_hashtag.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
