#!/usr/bin/env node
'use strict';

/**
 * Instagram: profile
 *
 *   --section=about -> /v1/instagram/profile-about — 3 credits
 *   --section=full -> /v1/instagram/profile-full — 3 credits
 *   --section=search -> /v1/instagram/profile-search — 2 credits per profile
 *   --section=similar -> /v1/instagram/similar — 2 credits
 *   --section=tagged -> /v1/instagram/tagged — 2 credits per post
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "about": { path: "/v1/instagram/profile-about", input: "handle", list: false },
  "full": { path: "/v1/instagram/profile-full", input: "handle", list: false },
  "search": { path: "/v1/instagram/profile-search", input: "query", list: true },
  "similar": { path: "/v1/instagram/similar", input: "handle", list: false },
  "tagged": { path: "/v1/instagram/tagged", input: "handle", list: true },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_profile.js <input> --section=<about|full|search|similar|tagged>\nSections: about, full, search, similar, tagged");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_profile.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
