#!/usr/bin/env node
'use strict';

/**
 * Instagram: transcript
 *
 *   (default) -> /v1/instagram/transcript — 40 credits
 *   --section=summary -> /v1/instagram/summary — 42 credits
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "default": { path: "/v1/instagram/transcript", input: "url" },
  "summary": { path: "/v1/instagram/summary", input: "url" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section || 'default';
if (!SECTIONS[section]) {
  usage("Usage: node get_transcript.js <input> [--section=<summary>]\nOmit --section for transcript (/v1/instagram/transcript).\nSections: summary");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_transcript.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
