#!/usr/bin/env node
'use strict';

/**
 * Instagram: location
 *
 *   --section=posts -> /v1/instagram/location-posts — 2 credits per post
 *   --section=search -> /v1/instagram/location-search — 2 credits per place
 *   --section=stats -> /v1/instagram/location-stats — 2 credits
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "posts": { path: "/v1/instagram/location-posts", input: "query" },
  "search": { path: "/v1/instagram/location-search", input: "query" },
  "stats": { path: "/v1/instagram/location-stats", input: "query" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_location.js <input> --section=<posts|search|stats>\nSections: posts, search, stats");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_location.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
