#!/usr/bin/env node
'use strict';

/**
 * Instagram: search
 *
 *   --section=keyword-search -> /v1/instagram/keyword-search — 2 credits per result
 *   --section=reels-search -> /v1/instagram/reels-search — 3 credits per result
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "keyword-search": { path: "/v1/instagram/keyword-search", input: "query" },
  "reels-search": { path: "/v1/instagram/reels-search", input: "query" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node search.js <input> --section=<keyword-search|reels-search>\nSections: keyword-search, reels-search");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node search.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
