#!/usr/bin/env node
'use strict';

/**
 * Escape hatch: call any YouTube endpoint by path, including ones that
 * have no dedicated script. Every flag after the path is passed through as a
 * query parameter.
 *
 *   node call_endpoint.js /v1/youtube/<capability> --handle nasa --limit 20
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, main, parseFlags, usage } = require('./_client.js');

const PREFIX = '/v1/youtube/';
const { _, flags } = parseFlags(process.argv.slice(2));
const path = _[0];

if (!path) {
  usage('Usage: node call_endpoint.js ' + PREFIX + '<capability> [--param value ...]');
}
if (!path.startsWith(PREFIX)) {
  usage('This script only calls ' + PREFIX + '* paths. Got: ' + path);
}

const params = {};
for (const [name, value] of Object.entries(flags)) {
  params[name] = value === true ? 'true' : value;
}

main(() => callEndpoint(path, params));
