#!/usr/bin/env node
'use strict';

/**
 * YouTube: media
 *
 *   --section=thumbnails -> /v1/youtube/thumbnails — 1 credit
 *   --section=video-audio -> /v1/youtube/video-audio — 3 credits
 *   --section=video-files -> /v1/youtube/video-files — 3 credits
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "thumbnails": { path: "/v1/youtube/thumbnails", input: "url", list: false },
  "video-audio": { path: "/v1/youtube/video-audio", input: "url", list: false },
  "video-files": { path: "/v1/youtube/video-files", input: "url", list: false },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_media.js <input> --section=<thumbnails|video-audio|video-files>\nSections: thumbnails, video-audio, video-files");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_media.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
