#!/usr/bin/env node
'use strict';

/**
 * YouTube: shorts
 *
 *   --section=hashtag-search -> /v1/youtube/shorts-hashtag-search — 2 credits per short
 *   --section=search -> /v1/youtube/shorts-search — 1 credit per short
 *   --section=trending -> /v1/youtube/shorts-trending — 2 credits per short
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "hashtag-search": { path: "/v1/youtube/shorts-hashtag-search", input: "query" },
  "search": { path: "/v1/youtube/shorts-search", input: "query" },
  "trending": { path: "/v1/youtube/shorts-trending", input: "none" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_shorts.js <input> --section=<hashtag-search|search|trending>\nSections: hashtag-search, search, trending");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_shorts.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
