#!/usr/bin/env node
'use strict';

/**
 * YouTube: transcript
 *
 *   (default) -> /v1/youtube/transcript — 3 credits
 *   --section=captions -> /v1/youtube/captions — 3 credits
 *   --section=subtitles -> /v1/youtube/subtitles — 1 credit
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "default": { path: "/v1/youtube/transcript", input: "url", list: false },
  "captions": { path: "/v1/youtube/captions", input: "url", list: false },
  "subtitles": { path: "/v1/youtube/subtitles", input: "url", list: false },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section || 'default';
if (!SECTIONS[section]) {
  usage("Usage: node get_transcript.js <input> [--section=<captions|subtitles>]\nOmit --section for transcript (/v1/youtube/transcript).\nSections: captions, subtitles");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_transcript.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
