#!/usr/bin/env node
'use strict';

/**
 * YouTube: comments
 *
 *   (default) -> /v1/youtube/comments — 1 credit per comment
 *   --section=comment-replies -> /v1/youtube/comment-replies — 1 credit per reply
 *   --section=top -> /v1/youtube/comments-top — 1 credit per comment
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "default": { path: "/v1/youtube/comments", input: "url" },
  "comment-replies": { path: "/v1/youtube/comment-replies", input: "url" },
  "top": { path: "/v1/youtube/comments-top", input: "url" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section || 'default';
if (!SECTIONS[section]) {
  usage("Usage: node get_comments.js <input> [--section=<comment-replies|top>]\nOmit --section for comments (/v1/youtube/comments).\nSections: comment-replies, top");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_comments.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
