#!/usr/bin/env node
'use strict';

/**
 * YouTube: trending
 *
 *   (default) -> /v1/youtube/trending — 2 credits per video
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "default": { path: "/v1/youtube/trending", input: "none", list: true },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const target = SECTIONS.default;

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_trending.js <' + target.input + '>' + '');
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
