#!/usr/bin/env node
'use strict';

/**
 * YouTube: channel
 *
 *   --section=lives -> /v1/youtube/channel-lives — 1 credit per stream
 *   --section=search -> /v1/youtube/channel-search — 2 credits per channel
 *   --section=shorts -> /v1/youtube/channel-shorts — 2 credits per short
 *   --section=stats -> /v1/youtube/channel-stats — 2 credits
 *   --section=top-videos -> /v1/youtube/channel-top-videos — 1 credit per video
 *   --section=videos -> /v1/youtube/channel-videos — 1 credit per video
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "lives": { path: "/v1/youtube/channel-lives", input: "handle" },
  "search": { path: "/v1/youtube/channel-search", input: "query" },
  "shorts": { path: "/v1/youtube/channel-shorts", input: "handle" },
  "stats": { path: "/v1/youtube/channel-stats", input: "handle" },
  "top-videos": { path: "/v1/youtube/channel-top-videos", input: "handle" },
  "videos": { path: "/v1/youtube/channel-videos", input: "handle" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_channel.js <input> --section=<lives|search|shorts|stats|top-videos|videos>\nSections: lives, search, shorts, stats, top-videos, videos");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_channel.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
