#!/usr/bin/env node
'use strict';

/**
 * YouTube: search
 *
 *   (default) -> /v1/youtube/search — 1 credit per result
 *   --section=hashtag-search -> /v1/youtube/hashtag-search — 2 credits per result
 *   --section=recent -> /v1/youtube/search-recent — 1 credit per result
 *   --section=streams-search -> /v1/youtube/streams-search — 1 credit per stream
 *   --section=suggestions -> /v1/youtube/search-suggestions — 1 credit per suggestion
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "default": { path: "/v1/youtube/search", input: "query", list: true },
  "hashtag-search": { path: "/v1/youtube/hashtag-search", input: "query", list: true },
  "recent": { path: "/v1/youtube/search-recent", input: "query", list: true },
  "streams-search": { path: "/v1/youtube/streams-search", input: "query", list: true },
  "suggestions": { path: "/v1/youtube/search-suggestions", input: "query", list: true },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section || 'default';
if (!SECTIONS[section]) {
  usage("Usage: node search.js <input> [--section=<hashtag-search|recent|streams-search|suggestions>]\nOmit --section for search (/v1/youtube/search).\nSections: hashtag-search, recent, streams-search, suggestions");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node search.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
