#!/usr/bin/env node
'use strict';

/**
 * Call any documented LinkedIn endpoint by path, including ones that
 * have no dedicated script. Only the paths listed in ALLOWED (the same set
 * documented in SKILL.md) are accepted; anything else is refused before a
 * request is made. Every flag after the path is passed through as a query
 * parameter.
 *
 *   node call_endpoint.js /v1/linkedin/<capability> --handle nasa --limit 20
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, main, parseFlags, usage } = require('./_client.js');

const PREFIX = '/v1/linkedin/';
const ALLOWED = new Set(["/v1/linkedin/ads-search","/v1/linkedin/comments","/v1/linkedin/company","/v1/linkedin/company-funding","/v1/linkedin/company-insights","/v1/linkedin/company-jobs","/v1/linkedin/company-people","/v1/linkedin/company-posts","/v1/linkedin/company-search","/v1/linkedin/job-search","/v1/linkedin/people-search","/v1/linkedin/people-search-by-name","/v1/linkedin/people-search-by-services","/v1/linkedin/post-comment-replies","/v1/linkedin/post-reactions","/v1/linkedin/profile","/v1/linkedin/profile-about","/v1/linkedin/profile-certifications","/v1/linkedin/profile-comments","/v1/linkedin/profile-contact","/v1/linkedin/profile-courses","/v1/linkedin/profile-educations","/v1/linkedin/profile-experiences","/v1/linkedin/profile-full","/v1/linkedin/profile-honors","/v1/linkedin/profile-languages","/v1/linkedin/profile-patents","/v1/linkedin/profile-posts","/v1/linkedin/profile-projects","/v1/linkedin/profile-publications","/v1/linkedin/profile-reactions","/v1/linkedin/profile-recommendations","/v1/linkedin/profile-similar","/v1/linkedin/profile-skills","/v1/linkedin/profile-stats","/v1/linkedin/profile-volunteers","/v1/linkedin/search","/v1/linkedin/stats"]);
const { _, flags } = parseFlags(process.argv.slice(2));
const path = _[0];

if (!path) {
  usage('Usage: node call_endpoint.js ' + PREFIX + '<capability> [--param value ...]');
}
if (!ALLOWED.has(path)) {
  usage(
    'This script only calls the documented ' + PREFIX + '* endpoints. Got: ' + path +
      '\nAllowed:\n  ' + [...ALLOWED].join('\n  ')
  );
}

const params = {};
for (const [name, value] of Object.entries(flags)) {
  params[name] = value === true ? 'true' : value;
}

main(() => callEndpoint(path, params));
