#!/usr/bin/env node
'use strict';

/**
 * LinkedIn: profile
 *
 *   (default) -> /v1/linkedin/profile — 10 credits (25 with include_email=true)
 *   --section=about -> /v1/linkedin/profile-about — 5 credits
 *   --section=certifications -> /v1/linkedin/profile-certifications — 5 credits
 *   --section=comments -> /v1/linkedin/profile-comments — 5 credits per comment
 *   --section=contact -> /v1/linkedin/profile-contact — 25 credits
 *   --section=courses -> /v1/linkedin/profile-courses — 5 credits
 *   --section=educations -> /v1/linkedin/profile-educations — 5 credits
 *   --section=experiences -> /v1/linkedin/profile-experiences — 5 credits
 *   --section=full -> /v1/linkedin/profile-full — 10 credits
 *   --section=honors -> /v1/linkedin/profile-honors — 5 credits
 *   --section=languages -> /v1/linkedin/profile-languages — 5 credits
 *   --section=patents -> /v1/linkedin/profile-patents — 5 credits
 *   --section=posts -> /v1/linkedin/profile-posts — 5 credits per post
 *   --section=projects -> /v1/linkedin/profile-projects — 5 credits
 *   --section=publications -> /v1/linkedin/profile-publications — 5 credits
 *   --section=reactions -> /v1/linkedin/profile-reactions — 5 credits per reaction
 *   --section=recommendations -> /v1/linkedin/profile-recommendations — 5 credits
 *   --section=similar -> /v1/linkedin/profile-similar — 5 credits
 *   --section=skills -> /v1/linkedin/profile-skills — 5 credits
 *   --section=stats -> /v1/linkedin/profile-stats — 5 credits
 *   --section=volunteers -> /v1/linkedin/profile-volunteers — 5 credits
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "default": { path: "/v1/linkedin/profile", input: "url|handle", list: false },
  "about": { path: "/v1/linkedin/profile-about", input: "url|handle", list: false },
  "certifications": { path: "/v1/linkedin/profile-certifications", input: "url|handle", list: false },
  "comments": { path: "/v1/linkedin/profile-comments", input: "url|handle", list: true },
  "contact": { path: "/v1/linkedin/profile-contact", input: "url|handle", list: false },
  "courses": { path: "/v1/linkedin/profile-courses", input: "url|handle", list: false },
  "educations": { path: "/v1/linkedin/profile-educations", input: "url|handle", list: false },
  "experiences": { path: "/v1/linkedin/profile-experiences", input: "url|handle", list: false },
  "full": { path: "/v1/linkedin/profile-full", input: "url|handle", list: false },
  "honors": { path: "/v1/linkedin/profile-honors", input: "url|handle", list: false },
  "languages": { path: "/v1/linkedin/profile-languages", input: "url|handle", list: false },
  "patents": { path: "/v1/linkedin/profile-patents", input: "url|handle", list: false },
  "posts": { path: "/v1/linkedin/profile-posts", input: "url|handle", list: true },
  "projects": { path: "/v1/linkedin/profile-projects", input: "url|handle", list: false },
  "publications": { path: "/v1/linkedin/profile-publications", input: "url|handle", list: false },
  "reactions": { path: "/v1/linkedin/profile-reactions", input: "url|handle", list: true },
  "recommendations": { path: "/v1/linkedin/profile-recommendations", input: "url|handle", list: false },
  "similar": { path: "/v1/linkedin/profile-similar", input: "url|handle", list: false },
  "skills": { path: "/v1/linkedin/profile-skills", input: "url|handle", list: false },
  "stats": { path: "/v1/linkedin/profile-stats", input: "url|handle", list: false },
  "volunteers": { path: "/v1/linkedin/profile-volunteers", input: "url|handle", list: false },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section || 'default';
if (!SECTIONS[section]) {
  usage("Usage: node get_profile.js <input> [--section=<about|certifications|comments|contact|courses|educations|experiences|full|honors|languages|patents|posts|projects|publications|reactions|recommendations|similar|skills|stats|volunteers>]\nOmit --section for profile (/v1/linkedin/profile).\nSections: about, certifications, comments, contact, courses, educations, experiences, full, honors, languages, patents, posts, projects, publications, reactions, recommendations, similar, skills, stats, volunteers");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_profile.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

if (flags.include_email) params.include_email = 'true';

main(() => callEndpoint(target.path, params));
