#!/usr/bin/env node
'use strict';

/**
 * LinkedIn: company
 *
 *   (default) -> /v1/linkedin/company — 10 credits
 *   --section=funding -> /v1/linkedin/company-funding — 10 credits
 *   --section=insights -> /v1/linkedin/company-insights — 10 credits
 *   --section=jobs -> /v1/linkedin/company-jobs — 5 credits per job
 *   --section=people -> /v1/linkedin/company-people — 5 credits per profile
 *   --section=posts -> /v1/linkedin/company-posts — 5 credits per post
 *   --section=search -> /v1/linkedin/company-search — 5 credits per company
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "default": { path: "/v1/linkedin/company", input: "url|handle", list: false },
  "funding": { path: "/v1/linkedin/company-funding", input: "url|handle", list: false },
  "insights": { path: "/v1/linkedin/company-insights", input: "url|handle", list: false },
  "jobs": { path: "/v1/linkedin/company-jobs", input: "url|handle", list: true },
  "people": { path: "/v1/linkedin/company-people", input: "url|handle", list: true },
  "posts": { path: "/v1/linkedin/company-posts", input: "url|handle", list: true },
  "search": { path: "/v1/linkedin/company-search", input: "query", list: true },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section || 'default';
if (!SECTIONS[section]) {
  usage("Usage: node get_company.js <input> [--section=<funding|insights|jobs|people|posts|search>]\nOmit --section for company (/v1/linkedin/company).\nSections: funding, insights, jobs, people, posts, search");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_company.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
