#!/usr/bin/env node
'use strict';

/**
 * LinkedIn: post
 *
 *   --section=comment-replies -> /v1/linkedin/post-comment-replies — 5 credits per comment
 *   --section=reactions -> /v1/linkedin/post-reactions — 5 credits per reaction
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "comment-replies": { path: "/v1/linkedin/post-comment-replies", input: "url" },
  "reactions": { path: "/v1/linkedin/post-reactions", input: "url" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section;
if (!section || !SECTIONS[section]) {
  usage("Usage: node get_post.js <input> --section=<comment-replies|reactions>\nSections: comment-replies, reactions");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node get_post.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
