#!/usr/bin/env node
'use strict';

/**
 * LinkedIn: people search
 *
 *   (default) -> /v1/linkedin/people-search — 5 credits per profile
 *   --section=by-name -> /v1/linkedin/people-search-by-name — 5 credits per profile
 *   --section=by-services -> /v1/linkedin/people-search-by-services — 5 credits per profile
 *
 * Generated by tools/generate.mjs. Do not edit by hand.
 */

const { callEndpoint, commonParams, main, parseFlags, usage } = require('./_client.js');

const SECTIONS = {
  "default": { path: "/v1/linkedin/people-search", input: "query" },
  "by-name": { path: "/v1/linkedin/people-search-by-name", input: "query" },
  "by-services": { path: "/v1/linkedin/people-search-by-services", input: "query" },
};

const { _, flags } = parseFlags(process.argv.slice(2));

const section = flags.section || 'default';
if (!SECTIONS[section]) {
  usage("Usage: node people_search.js <input> [--section=<by-name|by-services>]\nOmit --section for people-search (/v1/linkedin/people-search).\nSections: by-name, by-services");
}
const target = SECTIONS[section];

const value = _[0] || flags.url || flags.handle || flags.query;
const params = { ...commonParams(flags) };

if (target.input !== 'none') {
  if (!value) {
    usage('Missing input. Usage: node people_search.js <' + target.input + '>' + (section === 'default' ? '' : ' --section=' + section));
  }
  if (target.input === 'url|handle') {
    params[/^https?:\/\//i.test(value) ? 'url' : 'handle'] = value;
  } else {
    params[target.input] = value;
  }
}

main(() => callEndpoint(target.path, params));
